### ISSUE TITLE
Name of the julia package?

### ISSUE THREAD

**Issue by SylvainCorlay** [xtensor-stack/Xtensor.jl#14]
It could make sense for the julia package to be called `xtensor.jl`.

**Comment by sglyon** [comment]
My vote would be `Xtensor.jl`

**Comment by SylvainCorlay** [comment]
Note: that would merely for the name passed to `Pkg.add` since it only contains the examples

**Comment by sglyon** [comment]
Wouldn't it also be what users write to use the package?

As in

`using Xtensor`

**Comment by SylvainCorlay** [comment]
So the way people would use it is for writing julia bindings for C++ packages like with the `xtensor-python` package.

i.e. you pass a native Julia array to a function written in C++ which sees it as a valid xtensor array, on which you can use the high-level API instead of the C API of Julia.

Like here:
https://github.com/QuantStack/xtensor-python#example-2-create-a-universal-function-from-a-c-scalar-function

**Comment by SylvainCorlay** [comment]
At CraftCon, we should demo how you can write a C++ function operating on an N-D array, and expose it as a Julia package, and a Python package etc..
