### ISSUE TITLE
simplified test case (segfaults)

### ISSUE THREAD

**Issue by nbecker** [xtensor-stack/Xtensor.jl#50]
Here is a simplified test case
using julia-0.6rc, CxxWrap master

https://gist.github.com/nbecker/59054a8a7e3c94aea19fbd1af3eef611

**Comment by wolfv** [comment]
I've tried this code, and it does not segfault when not taking the reference to in the lambda. I'm closing this and the other issue for now.

We need to investigate if we can make passing by reference work.
